### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by Mgblugs** [amund7/EBikeLight#1]
This is a very cool mod.

Have you connected the control switch via a Y lead ?

Can you post a wiring diagram?

**Comment by amund7** [comment]
Thanks!
Not sure what you mean by Y lead?
Did you see the wiki? https://github.com/amund7/EBikeLight/wiki

I have some wiring photos in there. The switch is straight forward, 3 buttons, fed by+5v and the other end to respective inputs.

**Comment by Mgblugs** [comment]
I assume you are sharing the switch that is connected to the display? Control lights and PAS etc with same switch?

If the answer to above is yes then have you split the cable coming from the switch and wired parallel to the display and the Arduino? (Y lead)

I don't see the mosfet in the pictures?

Sorry! too many questions!

**Comment by amund7** [comment]
No this was just an extra Bafang switch I had, it is not connected to the display or controller at all. My BBSHD controller did not come with wires for lights (but I read some of them do)

The MOSFET is soldered directly to the arduino in the pictures, you can see the back of it, its legs are soldered to GND and D3. I desoldered the reset button from the arduino to package it nicer.

Power wiring is battery - to arduino GND pin of mosfet, - to lights solder to the back of the mosfet.
Battery + goes directly to lights.
This way, when Arduino adjusts PWM on D3, the mosfet will also open/close battery power directly to the lights.
The beauty with the whole ordeal is that my LED lights running on 50V will now dim beatifully with my switch, I can toggle full beam or dim as well as adjust how dim the dim setting should be. And I can run them straight off the main batteries for the bike.

Last note, the Arduino needs 5v or USB power from somewhere, I just plugged a short USB cable from the bafang display to the arduino. but note, I needed a ferrous core ring around it, otherwise the bike would accelerate slightly as soon as I turned the lights on!

**Comment by Mgblugs** [comment]
Many thanks for that. Much clearer now.
